### ISSUE TITLE
Apply button inactive

### ISSUE THREAD

**Issue by daniel-lo** [emoacht/HelloSwitcher#13]
Hi .. the headline sais it all .. can't do anything with the tool:

![grafik](https://user-images.githubusercontent.com/4311558/210252246-2b525126-29e8-4d09-a574-8d890dde725b.png)

Pls help

**Comment by emoacht** [comment]
I don't understand what is your problem. Could you elaborate it?

**Comment by daniel-lo** [comment]
The apply button is greyed.

**Comment by emoacht** [comment]
I see. It is because you have not selected Built-in camera.

**Comment by daniel-lo** [comment]
Intersting .. it's not a notebook. I guess I misunderstood the tool .. somewhere I read that it only helps if you have two hello compatible devices in the system ... which is not the case for me. I guess we can close here.
