### ISSUE TITLE
Re-check USB camera/disable built-in camera on app/service startup preferably before login screen

### ISSUE THREAD

**Issue by notuxius** [emoacht/HelloSwitcher#15]
Hi. I have two cameras with IR: zepherys laptop and brio. When i was using laptop separately - i needed my built-in camera to be enabled (as expected), but when i connected USB camera and login screen was shown after hibernation - the built-in camera was active for hello login, not the USB one. After opening the app and pressing Win+L - the built-in camera was active. And after pressing Re-check USB camera app menu item and Win+L - the USB camera was active (as expected). All this time Run as service checkbox was checked in the app settings. So i guess the app service should re-check USB camera on its startup and if one is present - forcedly disable the build-in and service should be high priority or something.
Windows 11 23H2, 1.6.0. Thank you.

**Comment by emoacht** [comment]
Have you tried to run as service? If so, what do you find after "Power Changed" in operation.service.log in "C:\ProgramData\HelloSwitcher" folder?

**Comment by emoacht** [comment]
Is your issue is re-check when the laptop is resumed? If so, could you try Ver 1.6.1 and see what happens?

**Comment by notuxius** [comment]
Yes, it's on the laptop. It's reproducible occasionally. Ok. i'll update and i'll watch what happens.

**Comment by notuxius** [comment]
Updated to 1.6.1. Saw just once that built-in camera was used first on lock screen, then after error in face recognition and after pressing Hello Face button on the same lock screen once again - the USB camera was used.

**Comment by emoacht** [comment]
I have no idea why the built-in camera could not be enabled. It might be a hardware restriction.
